### ISSUE TITLE
NuGet package 1.0.39 contains content from branch fluentui/desktop

### ISSUE THREAD

**Issue by szymon-checinski-digimuth** [adospace/fluent-ui-xaml#2]
NuGet package v1.0.39 for .NET Core 3.1 contains changes from fluentui/desktop.

Release versions should follow master branch, as currently it leads to issues when trying to follow the example project.

**Comment by adospace** [comment]
ops, yes, sorry forgot to update AppVeyor when added the new branch.
Upcoming version 1.0.40 should be built from the master branch.
