### ISSUE TITLE
System.InvalidCastException when DataGrid's AutoGenerateColumns set to True

### ISSUE THREAD

**Issue by szymon-checinski-digimuth** [adospace/fluent-ui-xaml#4]
**Steps to reproduce:**
1. Create a DataGrid with AutoGenerateColumns set to True
2. Bind it to a collection of objects for which not all columns have column definitions defined explicitly

**Expected result:**
DataGrid successfully generates missing columns

**Actual result:**
```
System.InvalidCastException
HResult=0x80004002
Message=Unable to cast object of type 'System.Windows.Controls.DataGridColumnCollection' to type 'System.Windows.Controls.DataGrid'.
Source=FluentUI
StackTrace:
at FluentUI.FabricHelper.<>c.<OnTextColumnStyleChanged>b__3_0(Object s, NotifyCollectionChangedEventArgs eventArgs)
at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
(...)
```

In FabricHelper.cs line 69 event sender is casted to DataGrid. When DataGrid adds a column automatically, sender is actually a DataGridColumnCollection

**Comment by adospace** [comment]
can you see if branch https://github.com/adospace/fluent-ui-xaml/tree/fix-issue-4 is working for you?

**Comment by szymon-checinski-digimuth** [comment]
Thanks, it works fine on this branch
