### ISSUE TITLE
Great project, please add "fluentui:FabricExtra.ErrorMessage" to all inpunt controls

### ISSUE THREAD

**Issue by 69mustang302** [adospace/fluent-ui-xaml#5]
Hi @adolfo-marinucci, thanks for this nice project which lets me easily modernize my older WPF appliction. I can give it the look&feel of my other Fleunt UI based  projects.

Have you considered adding the   `fluentui:FabricExtra.ErrorMessage` option (and required flag) to other input controls like ListBox, ComboBox etc?

If I have time I will give it a try, but current project presure leaves little or no space.

Thank you!

**Comment by adospace** [comment]
Added ErrorMessage for ComboBox, CheckBox and ListBox

**Comment by 69mustang302** [comment]
Thanks so much for the great solution!
